### ISSUE TITLE
move scores to playerdata/date

### ISSUE THREAD

**Issue by FubyCutie** [Holes-in-the-Code/hitw-economy-plugin#1]
create a new playerdata directory, where it will store data in the format of playerdata/DD.MM/UUID.json for scores

**Comment by Blackoutburst** [comment]
Are you sure you want to create a file for each day ? What are we gonna do with them in like 1 years * players the amount of I/O operation will be really stupidly huge and slow. I think it's better to have everything packed up inside a big file instead of multiples as a big request will never be as slow as thousand I/O operation

**Comment by Blackoutburst** [comment]
Or maybe you want to save these for a defined period of time and delete them after something like 90 days? In that case it's fine to do so and could be helpful with https://github.com/Holes-in-the-Code/hitw-economy-plugin/issues/4

**Comment by FubyCutie** [comment]
Done on bug/1 branch.
